export { default as Landing } from './landing/Landing';
export { default as Cart } from './cart/Cart';
export { default as Diary } from './diary/Diary';
export { default as MyPage } from './mypage/MyPage';
export { default as Recommend } from './recommend/Recommend';
export { default as Compare } from './cart/Compare';
export { default as Detail } from './detail/Detail';
export { default as Mbti } from './mbti/Mbti';
export { default as MbtiTest } from './mbti/MbtiTest';
